---
abstract: 'Subset of Unix::PID functionality with smaller memory footprint'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::MockFile: '0'
  Test::More: '0'
  Test::NoWarnings: '0'
  Test::Warn: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Unix-PID-Tiny
no_index:
  directory:
    - t
    - inc
requires:
  File::Slurp: '0'
  File::Temp: '0'
version: '0.94'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
